name: CI Pipeline

on: [push, pull_request]

jobs:
  lint-dockerfile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install hadolint
      run: |
        sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64
        sudo chmod +x /bin/hadolint
    - name: Lint Dockerfile
      run: hadolint ./Dockerfile

  test-app:
    needs: lint-dockerfile
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.15' # Sesuaikan dengan versi Go yang digunakan
    - name: Test
      run: go test -v -short --count=1 $(go list ./...)

  build-app-karsajobs:
    needs: test-app
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: yusufbagussh
        password: ${{ secrets.GHCR_PAT }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ghcr.io/yusufbagussh/karsajobs:latest

